### ISSUE TITLE
Merge vernacular names

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/xcol#10]
No associated information like vernacular names, name relations (e.g. basionym relations) or type information is copied on merge syncs. Allow syncs to also merge vernacular names

**Comment by camiplata** [comment]
@mdoering mentioned several weeks ago that this feature has been implement thus I will close the isse

**Comment by mdoering** [comment]
thanks. We haven't tested the outcomes much though. Sth we should definitely do!
