### ISSUE TITLE
Names to be excluded for merging in XCOL: to be added to the config file

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/xcol#101]
There are several names under "Incertae sedis" that do not add good / correct information to the extended release and should be labeled to filter them from the merging: 

https://www.dev.checklistbank.org/dataset/271349/classification?taxonKey=049c2210-cc29-40dd-b796-727d45d17dfd
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/ecda9330-29cf-4105-9d2d-d579c6527711)

These are the only examples found in the XCOL-2023-10-26 under Incertae sedis and they could be included in the config file as they are , however, in order to prevent merging names like those in future releases, we can make a RegEx that can detect the patterns: 
a)  names with a single letter or a single letter followed by a period. 
b) names begining with a "?" (question mark) followed by a string that does not correspond with a scientific name
c) names including "indet" without which leaves a illogical "canonical name" 
d) names endings that does not correspond to their taxon rank (i.e. genus ending in "ini" "inae" "aceae" ... etc
e) names of lower ranks equal to existing names in higher classification in the COL Checklist (i.e. genus Plantae)

**Comment by mdoering** [comment]
Implemented in code. Can be configured on dev in an hour

**Comment by mdoering** [comment]
available on prod now. You can test regular expressions nicely here (select java8 on the left):
https://regex101.com

Example https://regex101.com/r/B36fU6/1

**Comment by camiplata** [comment]
Several name have been excluded using this new feature
