### ISSUE TITLE
Families (and descendants) merged in xCOL even already in COL checklist

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/xcol#109]
Found in XCOL-2023-12-04 several cases o duplicates that show important errors in the merge: 

1.  Families placed directly under Animalia are duplicated with others properly located. 
Sources: IUCN and Official Lists and Indexes of Names in Zoology
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/8c9dfadd-7a27-4717-b603-0effe9ec4384)

2. the family [Aciculidae ](https://www.dev.checklistbank.org/dataset/275521/classification?taxonKey=~jxT) was merged even that it was already in COL Checklist. The family include genus and species with slight or no differences if compared to those existing previously in COL Checklist. 

![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/cdb0f48e-e3f7-4706-9892-0ecc76f730e0)

**Comment by mdoering** [comment]
For some reasons again there are names index matches missing ("Name Index Id"):
https://www.dev.checklistbank.org/dataset/275326/name/9b9ba0a1-0df8-4550-824f-8d06d107bc19

That causes the duplicates to be created. I'll try to figure out why that came about

**Comment by mdoering** [comment]
name matches of a release are copied from the project. And that also has the same shortage.
I am rematching both the project and the latest public release on dev.

I will also make sure that if there is no match existing when merging names, a new match will be done first

**Comment by mdoering** [comment]
Only one family left!
https://www.dev.checklistbank.org/dataset/277511/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&q=Aciculidae&sortBy=taxonomic

**Comment by camiplata** [comment]
Unit test done
