### ISSUE TITLE
Ideas to better manage duplicates created due to authorships

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#110]
On the xrelease  more than 30.000 duplicates are created when authorships do not match:

For example:

<img width="800" alt="Captura de pantalla 2024-01-15 a la(s) 12 57 41 p m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/c0465d58-3d01-41da-a86b-59fa62d81a57">

- https://www.dev.checklistbank.org/dataset/279769/taxon/~OqS
- https://www.dev.checklistbank.org/dataset/279769/taxon/~2UOU

Options to solve this case (when the names come from different sources):

1. If the canonical name and the higher taxonomy are a match keep the authorship of the dataset with higher priotity  and ignore the authorship of the sources with less priority. Do merge all other usefull elments such as synonyms, vernacular names among others.

2.  If the canonical name and the higher taxonomy are a match keep the authorship of the dataset with higher priotity and ignore completely the  names of the sources with less priority.

**Comment by mdoering** [comment]
The duplication did not happen because of different authorships, but because there were duplicate genera in different families created. Should be solved in the latest version, please reopen if not!
