### ISSUE TITLE
unmerged names derives on duplication

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#111]
The XCOL-2024-01-11 has several names that should had been merged, take for example the genus [Protoperidinium](https://www.dev.checklistbank.org/dataset/279769/duplicates?authorshipDifferent=true&category=uninomial&limit=50&minSize=2&mode=STRICT&q=Protoperidinium&status=accepted) that appears more than 50 times:

<img width="600" alt="Captura de pantalla 2024-01-15 a la(s) 3 24 23 p m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/6ce93343-78cd-4200-ad39-a26a025a31d8">

There are two problems:
1. sources were both scientific name an higher taxonomy are the same but weren't merged
2. The genus also appears multiple times from the same source, see the following names that are created from TAXREF BUT each repetition is associated with a different species of the genus:

- https://www.dev.checklistbank.org/dataset/279769/taxon/96cc3731-9de9-4609-a1cc-53ef92ff90a4 
- https://www.dev.checklistbank.org/dataset/279769/taxon/7f0855a1-0dc9-43e5-8323-c3522f4547a7
- https://www.dev.checklistbank.org/dataset/279769/taxon/19ac83e8-43b9-44f3-aed3-6acf885e9720
- https://www.dev.checklistbank.org/dataset/279769/taxon/4b982c0d-3ed1-4912-8a2e-eed57ee2e1ec

<img width="1097" alt="Captura de pantalla 2024-01-15 a la(s) 3 50 01 p m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/b241c10b-151d-4180-842e-64fa08f8c285">

This example is consistent with @DianRHR's finding of a 4x increase of duplicates between the last two xcol versions.

Also related to #87

**Comment by camiplata** [comment]
on the XCOL-2023-12-11 this did not happened

**Comment by mdoering** [comment]
This is still the case in the feb edition: https://www.dev.checklistbank.org/dataset/3LXRC/duplicates?authorshipDifferent=true&category=uninomial&limit=50&minSize=2&mode=STRICT&offset=0&q=Protoperidinium&status=accepted

**Comment by mdoering** [comment]
I can reproduce this nicely in tests. Working on some fix that will prevend many similar duplicates

**Comment by mdoering** [comment]
The genus [Protoperidinium](https://www.dev.checklistbank.org/dataset/283331/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&limit=50&offset=0&q=Protoperidinium&rank=genus&sortBy=taxonomic) only exists once now!

**Comment by camiplata** [comment]
unit test done
