### ISSUE TITLE
Issues showing wrong results: parent name mismatch and multiple basyonyms

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/xcol#112]
When selecting "parent name mismatch" from the issues of the XCOL-2024-01-11 it results on 2,547,413 names with that issue, however, that is not correct, this results includes names without any problem: 

https://www.dev.checklistbank.org/dataset/279769/taxon/~3RNe
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/a2b004de-d297-461a-9c05-20127fce8c77)

https://www.dev.checklistbank.org/dataset/279769/taxon/BLW9Q
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/20c2806b-2436-427d-84ca-9f102a956024)

https://www.dev.checklistbank.org/dataset/279769/taxon/9C8T6
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/e880be43-4d4b-4377-aa32-6a10889f21c6)

**When selecting "multiple basyonyms" from the issues of the XCOL-2024-01-11 shows a total of 1,604,513 names, however, when selecting the issue, the number of names changes to 576,752 with that issue, however,  the results include names without that problem:**

![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/d3a286c9-c04b-4632-8fda-080b2374c0ca)

https://www.dev.checklistbank.org/dataset/279769/nameusage/BM2Y6
Data shown in the original source: 
https://www.dev.checklistbank.org/dataset/1008/taxon/Reptilia-Squamata-Colubroidea-Colubridae-Colubrinae-Ptyas%20dhumnades-674b422746fe92bb3b126bf8734f4adf

**Comment by camiplata** [comment]
Issue still present in the last releases

<img width="896" alt="Captura de pantalla 2024-03-15 a la(s) 11 04 47 a m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/631e36f5-c550-48bc-80e2-91c11f7c510f">

<img width="1190" alt="Captura de pantalla 2024-03-15 a la(s) 11 05 03 a m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/8247ce91-0403-45f0-9329-1c9896adddff">

**Comment by DianRHR** [comment]
Issue "parent name mismatch" is still present in the last release
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/afe83d16-aac4-4501-adda-2060e50b1cfd)
