### ISSUE TITLE
Fuzzy comparison in authors not working properly

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/xcol#113]
In the XCOL-2024-02-02 I found that there are duplicates in names that have minor differences between an existing name in the COL Checklist and  another merged from a new source. 

Differences in 1 letter in the author, same name, same status and same rank should be avoided and the "new" name must be ignored. 

Example Abbella zabinskii 
https://www.dev.checklistbank.org/dataset/282644/classification?taxonKey=4CNZR
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/06ef3004-a276-4a30-8d74-861392b1ac90)

Abbella zabinskii No**v**icki, 1936 from UCD in COL Checklist (Synonym of Paracentrobia zabinskii (No**v**icki, 1936)
Abbella zabinskii No**w**icki, 1936 from FaEu in XCOL (Synonym of Paracentrobia zabinskii (No**w**icki, 1936)

In this case, both the synonym and the valid name are duplicating with those existent in COL Checklist. 

The log file showed this: 
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/897cb918-27db-4692-9b98-43705373bec0)

**Comment by mdoering** [comment]
Still exists in the latest release:
https://www.dev.checklistbank.org/dataset/3LXRC/names?q=Abbella%20zabinskii

**Comment by mdoering** [comment]
I dont think this has to do with authorships and matching. You can see here they both match to the same COL usage:

https://api.dev.checklistbank.org/dataset/3LR/match/nameusage?q=Abbella%20zabinskii%20Novicki,%201936
https://api.dev.checklistbank.org/dataset/3LR/match/nameusage?q=Abbella%20zabinskii%20Nowicki,%201936

**Comment by mdoering** [comment]
It indeed is an authorship comparison problem. The current code requires the first 4 characters to be the same. I will add a true fuzzy comparison in addition to that

**Comment by camiplata** [comment]
unite test added
