### ISSUE TITLE
Investigate into missing OTU name

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/xcol#116]
There seem to be problems in adding OTUs into the XCOL. It claims to have OTU names in metrics, but the search doesnt find them and if you browse for known ones they are also not present. Maybe just base names, I'll investigate for example the BOLD record BOLD:AAG1284
https://www.gbif.org/species/9849195

Exists twice in the BOLD dataset in CLB 
https://www.dev.checklistbank.org/dataset/37384/names?facet=rank&facet=issue&facet=status[…]Mode&limit=50&offset=0&q=BOLD%3AAAG1284&sortBy=taxonomic

 - https://www.dev.checklistbank.org/dataset/37384/verbatim/421849
 - https://www.dev.checklistbank.org/dataset/37384/verbatim/1811588

**Comment by camiplata** [comment]
The OTU's are there, apparently is a search/browse issue

<img width="400" alt="Captura de pantalla 2024-03-15 a la(s) 11 07 54 a m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/5ba093f7-0821-48da-baec-d9673717e07c">
<img width="400" alt="Captura de pantalla 2024-03-15 a la(s) 11 10 08 a m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/78364d08-d690-47ad-b22e-bb647271f4b0">

**Comment by DianRHR** [comment]
The [search ](https://www.checklistbank.org/dataset/298210/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&q=BOLD%3AAAG1284&sortBy=taxonomic) of OTU and [metrics ](https://www.checklistbank.org/dataset/298210/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&nameType=otu&offset=0&rank=unranked&reverse=false&sectorMode=merge&sortBy=name)are showing the merged OTU names in the last [release](https://www.checklistbank.org/dataset/298210/about) properly.
