### ISSUE TITLE
Families from IUCN wrongly merged directly under Animalia generating duplicates

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/xcol#117]
In the releases  XCOL-2024-02-16 and in  XCOL-2024-03-02  >500 families (source: IUCN) were included directly under Animalia. Most of them are already part of the tree in the COL Checklist, so they shouldn't be merging and generating duplicates. The names are writen exactly in both parts.
 Also,  most of them were merged without children (genera or species): 
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/b8a6f5e4-66ac-4afe-9062-55a9145b4f2d)

There is no pattern on the families that have children, some of the descendants are as well duplicated but some are not duplicated, but were merged under the family placed under Animalia.

In the specific case of the family Artamidae, the IUCN dataset includes both its higher taxonomy (within Passeriformes) and the genus Melloria with one species. The merging included correctly 5 subspecies (from IOC) and 1 OTU from BOLD 
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/361e419c-6f90-4196-b146-1694e1f9d23b)

**Comment by camiplata** [comment]
This has been fixed on 2024-06-08[X-Release](https://www.checklistbank.org/dataset/298210)
