### ISSUE TITLE
Same name, same author, different sources : difference in capital letters generating duplicates

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/xcol#120]
The list of synonyms of [Chelonia mydas](https://www.dev.checklistbank.org/dataset/285035/taxon/TVGD) includes the same name with the same author more than once, coming from different sources, where the use of capital letters is the only difference. 
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/33345bc6-0ab9-4089-9199-c6839aaaeade)

Checking the names in their original sources, shows that their taxonomy is the same: 
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/12c8c58a-52c6-4155-85eb-eb41193e88a6)
https://www.dev.checklistbank.org/dataset/285035/nameusage/~3UBv

and 
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/27e0baac-de93-4875-92bc-d59f76e30c1e)
https://www.dev.checklistbank.org/dataset/285035/nameusage/~NNs

These two names must be considered to be the same one and and priority would be to the ITIS name.

**Comment by DianRHR** [comment]
The error persist in last release: 
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/ad4e32d1-8bf0-45fe-8295-391308924485)

![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/3a501b1b-e64b-4723-a783-7ea45f6b9ca0)

**Comment by mdoering** [comment]
https://www.checklistbank.org/dataset/298210/name/3mXkS9wuxFPy5lEE9j6qr0
https://www.checklistbank.org/dataset/298210/name/~2mK3

One is of rank `infraspecific_name` and one is `subspecies`, maybe that has an impact. The parsed authorship and epithets are entirely the same otherwise.

**Comment by mdoering** [comment]
The issue was not on our project board btw

**Comment by mdoering** [comment]
fixed in https://github.com/CatalogueOfLife/backend/commit/71560f62c2e0b0879f7d71bbad89ba76f7631856
