### ISSUE TITLE
Species of the synonym genus 'Cactus' were merged under the valid genus Mammillaria  

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/xcol#121]
The genus 'Cactus' is a synonym genus of Mammillaria in the COL. However, in the extended rekease species of the genus 'Cactus' were merged as valid species under Mammillaria. 
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/b5ecf06f-2a15-40e0-bca1-f35881d51d93)

In the xCOL [Cactus ](https://www.dev.checklistbank.org/dataset/285035/taxon/5KS4 )is a ynonym so, the species wich combination includes 'Cactus' shouldn't be merged as valid under mammallia. 
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/d757fd37-4129-4a49-bf90-d0b0d104c189)

**Comment by mdoering** [comment]
What should else be done to them? We cannot create new combinations and move them to the genus Mammillaria automatically without a source saying so. Although this would be legal in zoology (clearly not in botany) we decided COL does not want to create new combinations, hence these species are left with their original name and should get a provisional status. The outcome is expected to me

**Comment by mdoering** [comment]
If you want pose the question to the TG today

**Comment by DianRHR** [comment]
We lowered the priority to TPL sector, so the species are merging now under Opuntia (GRIN considers Cactus a synonym of Opuntia). GRIN has higher priority than TPL in the COL project, so the priorities are working fine in the merged sectors.

In the last release Cactus has three homonyms with three different accepted names: 
Cactus L. = Mammillaria
Cactus Lem. = Opuntia
Cactus Britton & Rose = Melocactus
 
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/4a2b89bd-e029-483d-9c67-846ed34e28a3)

 However, in the baseCOL, **Cactus** L. is synonym of [Mammillaria ](https://www.checklistbank.org/dataset/299029/taxon/5KS4). 
@mdoering  As the **Cactus** species comes from TPL, which includes the genus [Cactus (without author) ](https://www.checklistbank.org/dataset/2039/taxon/xBQZ) as an accepted name, shouldn't all its species be merged below Mammillaria, independently of the homonyms in the merged sectors?.

**Comment by mdoering** [comment]
This is a difficult case. I am not sure even if the procedure to place species under the accepted name of the genus - without recombining it - makes sense. Often genera are split and only partially a synonym. It does not mean all species are now also to be moved.

In this case the baseCOL has all Cactus names indeed under the genus Mammilaria:
https://www.checklistbank.org/dataset/299029/names?TAXON_ID=5KS4&q=Cactus&rank=species

**Comment by DianRHR** [comment]
In the last xrelease is happening the same, Cactus species are merging under [Opuntia](https://www.checklistbank.org/dataset/299805/classification?taxonKey=69B3).

**Comment by mdoering** [comment]
If there are several Cactus synonyms the merge does not automatically match the highest priority one, but it is rather based on name and classification matching. Adding an integration test now

**Comment by mdoering** [comment]
I think the reason is Lem. and L. get confused somewhere during merging - I just cant find where...

**Comment by DianRHR** [comment]
The Cactus species from TPL were all merged below Mammillaria in the latest release. All of them as "provisionally accepted" .
