### ISSUE TITLE
Test adding dataset  with conflicting  authorship names to check merging

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#125]
On previous dev test the name [Ligularia robusta (Ledeb.) DC](https://www.dev.checklistbank.org/dataset/289237/taxon/~6f2Y) has been added as an accepted name although [the base COL has it as a synonym.](https://www.dev.checklistbank.org/dataset/289237/taxon/7Z6X7)

Add the ["Red List of Altai Mountain Country (plants)"](https://www.dev.checklistbank.org/dataset/23910/about), in prod to check if the merge works or not.

The only difference between sources is a period

[Ligularia robusta (Ledeb.) `DC.`](https://www.dev.checklistbank.org/dataset/289237/nameusage/7W49R) vs [Ligularia robusta (Ledeb.) `D.C.`](https://www.dev.checklistbank.org/dataset/289237/taxon/~6f2Y)

[List of merged names on dev test](https://www.dev.checklistbank.org/dataset/289237/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&sectorDatasetKey=23910&sortBy=taxonomic)

**Comment by camiplata** [comment]
Sector added to be review on next xrelease

**Comment by mdoering** [comment]
Consider adding to [authormap](https://github.com/CatalogueOfLife/backend/blob/9f3c1c2a50da70243dbb1bf4808a3f7745a96dff/api/src/main/resources/authorship/authormap.txt#L1060) for the author comparator
