### ISSUE TITLE
Delete Families and genera with no species?

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#133]
@mdoering from issue #7 I understand that the desired behavior for the xrelease is to remove empty families or genera? Currently we are keeping them, I think is valuable to have them 

For example the merged [Astacura](https://www.checklistbank.org/dataset/298754/taxon/D3KRN) has [1000 + occurrenes on GBIF](https://www.gbif.org/occurrence/search?taxon_key=11137500)
<img width="791" alt="Captura de pantalla 2024-06-27 a la(s) 1 16 09 p m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/bc46f197-1940-4e1e-8e5b-36a800da9c15">

**Comment by mdoering** [comment]
we only delete empty merged genera which often result of old species combinations that are turned into synonyms. Some, maybe many of these genera are not accepted any longer.
