### ISSUE TITLE
Create classification to better place arthropoda

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#140]

**Comment by camiplata** [comment]
@mdoering Here it is the classification  on the github repo, https://github.com/CatalogueOfLife/higherclassification_xrelease/blob/main/taxonomy.txtree

Which are the next steps to connect this repo with CLB?

**Comment by mdoering** [comment]
basically follow the guide of the template: https://github.com/CatalogueOfLife/higherclassification_xrelease?tab=readme-ov-file#github-webhooks

 - create an external dataset in CLB
 - configure it 
 - configure the github hooks as outlined above

You should then also update the readme and remove the template defaults.
I would also think we should make all our data repos public - unless there is a very good reason not to do so.

**Comment by mdoering** [comment]
The metadata.yaml needs some cleanup. I would also call it differently so that it is clear it belongs to COL.
Instead of:

>title: Higher classification patch for the extended release
alias: HC_Xrelease

maybe this?
>title: Catalogue of Life classification patch
alias: HC_XCOL

**Comment by mdoering** [comment]
Another convention we agreed on is to prefix all COL data repos in github with `data-`. 
Better rename this repo to sth like `data-classification-patch`.

**Comment by mdoering** [comment]
How many "patch" datasets do you envision to create?  From the top of my head I know of
 - https://github.com/CatalogueOfLife/data-paleo-tree
 - https://github.com/CatalogueOfLife/data-xcol-patch
 - https://github.com/CatalogueOfLife/higherclassification_xrelease
 
I think those 3 make sense. Keep the xcol patch for low level patches, put all classification gap into this new one and keep the palaeo one distinct for collaboration?

**Comment by camiplata** [comment]
Simplifications made from  original  [Ruggiero et al. 2015 ](https://www.checklistbank.org/dataset/294066/about)

-  Arachnida [class] #  "should" be under Euchelicerata [class]
-  Copepoda [class] #  "should" be under  Maxillopoda


Merostomata [class] was keep as a class under chelicerata according to [worms](https://www.marinespecies.org/aphia.php?p=taxdetails&id=150507) an [ITIS](https://www.checklistbank.org/dataset/2144/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&q=Merostomata&sortBy=taxonomic), this class is missing from Ruggiero et al. 2015. Nevertheless acording to Dave note on [this issue](https://github.com/CatalogueOfLife/data/issues/648), Xiphosura will be kept instead of Merostomata. So we will need to make some changes later.

**Comment by mdoering** [comment]
Please document the reasons for the classification (changes) in its repository, not this issue. 
Either as an issue or when committing changes to the tree in git. Or best even in a simple changes.md document - you can reach out to github issues from there too.

**Comment by mdoering** [comment]
Did it merge fine? Looks ok at first glance, but haven't checked all details:

<img width="684" alt="image" src="https://github.com/user-attachments/assets/c539c26b-9628-4f74-9889-c2d51ccdf9dd">
