### ISSUE TITLE
Evaluate the benefit of using TPL as a source for xrelease

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/xcol#145]
TPL is a valuable source for literature in plants, however, the names listed have not been evaluated for a long time, and it also includes unchecked names, whose taxonomic status is uncertain. 

Thus, it might be convenient to only merge the relevant taxonomy in the xrelease.

**Comment by DianRHR** [comment]
See also #131 and #121

**Comment by camiplata** [comment]
also related to: https://github.com/orgs/CatalogueOfLife/projects/3/views/1?pane=issue&itemId=70198169

**Comment by camiplata** [comment]
We put back TPL now only providing references
