### ISSUE TITLE
Same genus (from different sources) merging twice or more

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/xcol#146]
Several genus in family Ancistrocomidae (which was wrongly merged in Gentianales) were merged more than once, even if they have the same authority or a third source didn't include the authority. 

https://www.checklistbank.org/dataset/299805/classification?taxonKey=CV46W

![image](https://github.com/user-attachments/assets/2081a3d5-e17b-4aca-87a3-e1b185587014)

**Comment by camiplata** [comment]
[Unite test failed on the latest release](https://www.checklistbank.org/dataset/3LXRC/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&q=Ancistrocoma&rank=genus&sortBy=taxonomic&status=accepted)


<img width="1126" alt="Captura de pantalla 2024-07-24 a la(s) 6 44 41 a m" src="https://github.com/user-attachments/assets/cb5dbdb0-7eea-4ed1-a234-6794e7295841">
<img width="1133" alt="Captura de pantalla 2024-07-24 a la(s) 6 44 59 a m" src="https://github.com/user-attachments/assets/e2657854-03d0-4b8b-92ce-0974a095a6db">

**Comment by DianRHR** [comment]
The problem persists in the last [xrelease](https://www.checklistbank.org/dataset/301258/about) in [Ancistrocoma](https://www.checklistbank.org/dataset/301258/classification?taxonKey=DF4YH), [Hypocomella](https://www.checklistbank.org/dataset/301258/classification?taxonKey=DF4YR) and several genus listed in the task "Identical genus" like [Acrochaetium](https://www.checklistbank.org/dataset/301258/classification?taxonKey=FT3Z6), where the expected behavior would be to merge only the genus from IRMNG (priority over BOLD) and only merge from BOLD the species that are not included in the other sources.

**Comment by camiplata** [comment]
| issue_146_1 | succeded | https://github.com/CatalogueOfLife/xcol/issues/146 | https://www.checklistbank.org/dataset/3LXRC/names?q=Ancistrocoma&rank=genus&sortBy=taxonomic&status=accepted |
| issue_146_2 | succeded | https://github.com/CatalogueOfLife/xcol/issues/146 | https://www.checklistbank.org/dataset/3LXRC/names?q=Hypocomella&rank=genus&sortBy=taxonomic&status=accepted |

**Comment by camiplata** [comment]
Acanthosiphonia should be only once, the BOLD genus shouldn't be added as it has the lowest priority
<img width="1182" alt="Captura de pantalla 2024-08-21 a la(s) 3 02 52 p m" src="https://github.com/user-attachments/assets/a0e032f5-345c-4253-a846-fbfd767cfb3c">

**Comment by camiplata** [comment]
issue_146_Acrochaetium | failed | https://github.com/CatalogueOfLife/xcol/issues/146 | https://www.checklistbank.org/dataset/3LXRC/names?q=Acrochaetium&rank=genus&sortBy=taxonomic&status=accepted
-- | -- | -- | --
issue_146_Acanthosiphonia | failed | https://github.com/CatalogueOfLife/xcol/issues/146 | https://www.checklistbank.org/dataset/3LXRC/names?q=Acanthosiphonia&rank=genus&sortBy=taxonomic&status=accepted

**Comment by DianRHR** [comment]
Another example is [Crotalaria ]([url](https://www.checklistbank.org/dataset/301711/classification?taxonKey=1273c91c-28c5-4e78-b15c-e738c7e62c77)) and almost all the species below are duplicated.

**Comment by camiplata** [comment]
issue_146_Acrochaetium | failed | https://github.com/CatalogueOfLife/xcol/issues/146 | https://www.checklistbank.org/dataset/3LXRC/names?q=Acrochaetium&rank=genus&sortBy=taxonomic&status=accepted
-- | -- | -- | --
issue_146_Acanthosiphonia | failed | https://github.com/CatalogueOfLife/xcol/issues/146 | https://www.checklistbank.org/dataset/3LXRC/names?q=Acanthosiphonia&rank=genus&sortBy=taxonomic&status=accepted

**Comment by DianRHR** [comment]
Another example is [Aphanizomenon ](https://www.checklistbank.org/dataset/303772/classification?taxonKey=Y9L) which is provided by ITIS with an outdated classification (in family Nostocaceae); 9 records (species and below) are merging below it from different sources.
And [Aphanizomenon ](https://www.checklistbank.org/dataset/303772/classification?taxonKey=DQNHC) which is merging below family Aphanizomenonaceae, both family and genus are merged from WoRMS with just 1 species.  
The difference in this case is the higher classification and the way of citing the author: Aphanizomenon Morren, 1888 Ex Bornet & Flahault vs  Aphanizomenon Morren ex Bornet & Flahault. ALthough, it is clearly the same author.

**Comment by mdoering** [comment]
The ITIS one is also given with code=bacterial, while Dyntaxa has no code. WoRMS provides the family, but genus and species come from Dyntaxa.

This should clearly not happen.
If you look into the build logs I cannot trace what is going on. We do not seem to log all events, looks like the wrong debug level is used. But I can see lots and lots of species like these from NCBI are also dropped, but I suppose that is desired:
```
2169 Ignore SPECIES Aphanizomenon flos-aquae [1176] because RANK: SPECIES
2169 Ignore SPECIES Aphanizomenon elenkinii Kisselev, 1951 [2651365-s1] because IGNORED_PARENT: 2651365
2169 Ignore SPECIES Aphanizomenon gracile M4/1a [168378-s1] because IGNORED_PARENT: 168378
2169 Ignore SPECIES Aphanizomenon gracile M41/b [168378-s2] because IGNORED_PARENT: 168378
```

**Comment by mdoering** [comment]
Yes, we only log on debug level in DEV and since we moved to prod forgot to change the setting.
I will change that for tomorrows release - the build logs are crucial to understand whats going on, please use them!

**Comment by mdoering** [comment]
Which are the genera being still duplicated in the latest 2024-10-12 release?

[Aphanizomenon](https://www.checklistbank.org/dataset/304443/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&q=Aphanizomenon&sortBy=taxonomic) looks ok to me. Just a typo for a binomen which will be handled by a new [orth var detection feature](https://github.com/CatalogueOfLife/backend/issues/1363).
Aphanizomenon holsaticum Richter
Aphanizomenon holtsaticum Richter

And some NCBI strains that should better be removed in the next release.

**Comment by camiplata** [comment]
issue_146_1 | succeded | https://github.com/CatalogueOfLife/xcol/issues/146 | https://www.checklistbank.org/dataset/3LXRC/names?q=Ancistrocoma&rank=genus&sortBy=taxonomic&status=accepted
-- | -- | -- | --
issue_146_2 | succeded | https://github.com/CatalogueOfLife/xcol/issues/146 | https://www.checklistbank.org/dataset/3LXRC/names?q=Hypocomella&rank=genus&sortBy=taxonomic&status=accepted
issue_146_Acrochaetium | failed | https://github.com/CatalogueOfLife/xcol/issues/146 | https://www.checklistbank.org/dataset/3LXRC/names?q=Acrochaetium&rank=genus&sortBy=taxonomic&status=accepted
issue_146_Acanthosiphonia | succeded | https://github.com/CatalogueOfLife/xcol/issues/146 | https://www.checklistbank.org/dataset/3LXRC/names?q=Acanthosiphonia&rank=genus&sortBy=taxonomic&status=accepted

**Comment by mdoering** [comment]
I suspect it is the tax group analyzer from the matching that is causing Acrochaetium to fail.
The [IBOL](https://www.checklistbank.org/dataset/37384/taxon/53919) version of it is placed in Protista and ends up (correctly) as an algae:
> kingdom: [Protista](https://www.checklistbank.org/dataset/37384/taxon/Protista) >phylum: [Rhodophyta](https://www.checklistbank.org/dataset/37384/taxon/48327) >class: [Florideophyceae](https://www.checklistbank.org/dataset/37384/taxon/96) >order: [Acrochaetiales](https://www.checklistbank.org/dataset/37384/taxon/50268) >family: [Acrochaetiaceae](https://www.checklistbank.org/dataset/37384/taxon/50269) >genus: [Acrochaetium](https://www.checklistbank.org/dataset/37384/classification?taxonKey=53919)




PS: [Acrochaetium](https://www.checklistbank.org/dataset/304591/taxon/NCD) also contains synonym species from TaxRef
>[= Acrochaetium hirsutum (K.M.Drew) P.W.Gabrielson](https://www.checklistbank.org/dataset/304591/nameusage/D9PSY) m [[source: 2008]](https://www.checklistbank.org/dataset/304591/taxon/NCD#col-sourcedataset-2008)
[≡ Chromastrum hirsutum (K.M.Drew) Papenf., 1945](https://www.checklistbank.org/dataset/304591/nameusage/D9PSZ) m [[source: 2008]](https://www.checklistbank.org/dataset/304591/taxon/NCD#col-sourcedataset-2008)
[≡ Kylinia hirsuta (K.M.Drew) Kylin, 1944](https://www.checklistbank.org/dataset/304591/nameusage/D9PSW) m [[source: 2008]](https://www.checklistbank.org/dataset/304591/taxon/NCD#col-sourcedataset-2008)
[≡ Rhodochorton hirsutum K.M.Drew, 1928](https://www.checklistbank.org/dataset/304591/nameusage/D9PT4) m [[source: 2008]](https://www.checklistbank.org/dataset/304591/taxon/NCD#col-sourcedataset-2008)

**Comment by mdoering** [comment]
The BOLD input results in `protists`:
https://api.checklistbank.org/parser/taxgroup?q=Acrochaetium&kingdom=Protista&phylum=Rhodophyta&class=Florideophyceae&order=Acrochaetiales&family=Acrochaetiaceae&genus=Acrochaetium

The algae taxgroup dictionaries are very sparse. I will update them based on the 2024 Guiry publication which I uploaded here: https://www.checklistbank.org/dataset/304685/about
