### ISSUE TITLE
xrelase 2024-08-25

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#160]
## changelog:
- Checklist Dutch Caribbean Species Register, only species will be added https://github.com/CatalogueOfLife/xcol/issues/135
- New fix to the hymenoptera patch https://github.com/CatalogueOfLife/xcol/issues/127
- Remove a Rocha Keyna, and add only selected datasets see https://github.com/CatalogueOfLife/xcol/issues/163
- Add Checklist of Cyanobacteria of Greece
- Block Animalia genera
- Add AusMoss Darwin Core Archive

## Summary

No significant changes in number of issues, duplicates or general metrics.

## Unit test results:
Only failed tests are listed

issue_146_Acrochaetium | failed | https://github.com/CatalogueOfLife/xcol/issues/146 | https://www.checklistbank.org/dataset/3LXRC/names?q=Acrochaetium&rank=genus&sortBy=taxonomic&status=accepted
-- | -- | -- | --
issue_146_Acanthosiphonia | failed | https://github.com/CatalogueOfLife/xcol/issues/146 | https://www.checklistbank.org/dataset/3LXRC/names?q=Acanthosiphonia&rank=genus&sortBy=taxonomic&status=accepted

## ISSUES
Relevant issues from previous release

- missing genus
- parent species missing
- published before genus
- synonym parent

## Duplicate
Relevant issues from previous release

- ACC-SYN_infra_diff_acc_eq_auth
- any_uninomial
- ident_genus

**Comment by DianRHR** [comment]
- Block Animalia genera
- Add Annotated checklist of endemic species from the Western Balkans  [301539](https://www.checklistbank.org/dataset/301539/classification)
