### ISSUE TITLE
name typo in plazi

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/xcol#167]
<img width="444" alt="image" src="https://github.com/user-attachments/assets/636b79f6-ae5d-4824-94e5-a4db24b77313">

**Comment by DianRHR** [comment]
It's not a typo from Plazi, the article was published with the typo.
![image](https://github.com/user-attachments/assets/f46508b6-1bb7-4403-bc06-76978e456cf3)

![image](https://github.com/user-attachments/assets/8f5e7d4f-6b04-44b5-a192-66478b4296d5)

So Plazi has nothing to fix here. It must be a kind of errata published by Zootaxa. 
I blocked the name in the xcol-config.yaml

**Comment by mdoering** [comment]
Better than blocking would be to keep it as an orthographic variant in the synonymy.
That's done by adding an editorial `update` decision (=complex decision in the UI) to the plazi name and setting `keepOriginalName`=true.

This way also subsequent names with that typo get directed to the real one.

**Comment by DianRHR** [comment]
the decision was included in CLB without including authors, to point to any name with that spelling in that family , independently of the authority.

**Comment by mdoering** [comment]
Thanks @DianRHR 
The updated name is the same as the original subject though:
https://www.checklistbank.org/catalogue/3/decision?limit=100&name=Phlegra&offset=0

<img width="662" alt="image" src="https://github.com/user-attachments/assets/8f735948-e6b2-4951-b7ac-edcd6d292065">

I have changed the decision to update the name to _Phlegra fasciata_ and authorship `(Hahn, 1826)` instead.
