### ISSUE TITLE
Missing merge of synonym relationship - Platystoma seminationis case

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#174]
[Platystoma seminationis (Fabricius, 1775)](https://www.checklistbank.org/dataset/301904/taxon/4JZ9P) is a dipteran name from COL base and the xrelease adds several synonyms.

[Reviewing this issue ](https://github.com/gbif/backbone-feedback/issues/530) I noticed that the merge is not adding the following synonym relationship:  [Platystoma seminatione (Fabricius, 1775)](https://www.checklistbank.org/dataset/2008/nameusage/257762) as a synonym of Platystoma seminationis (Fabricius, 1775) from TAXREF.  And this relationship should have priority over the National Checklist of all species occurring in Denmark  [where it is an accepted name](https://www.checklistbank.org/dataset/9712/taxon/MSTSNM%3AArter%3Ab6828177-67d4-4655-b32c-abc800da056e).

**Comment by mdoering** [comment]
That's expected. After a latin stemming of `seminationis` and `seminatione` both end up to be semination so its considered to be the same name and is not created as an additional synonym. Is that causing any problem elsewhere? The original issue is about GBIF

**Comment by camiplata** [comment]
@mdoering then GBIF needs to adjust their matching process so the occurrences of  Platystoma seminatione are mapped to Platystoma seminationis? or what we or they should do to have those occurrences correctly placed?

**Comment by mdoering** [comment]
They both match already
 - http://api.gbif.org/v1/species/match?name=Platystoma%20seminatione
 - http://api.gbif.org/v1/species/match?name=Platystoma%20seminationis
