### ISSUE TITLE
blocked? Silene tenuiflorus Griseb.

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#176]
see [this issue](https://github.com/gbif/backbone-feedback/issues/528)

**Comment by DianRHR** [comment]
The name Silene tenuiflorus doesn't exist. I searched in [Caryophyllales.org](https://caryophyllales.org/cdm_dataportal/taxon/1cf1141a-34b9-4678-b50f-6170b6a2963a), in [BHL ](https://www.biodiversitylibrary.org/search?searchTerm=Silene+tenuiflorus&stype=F#/names) and there is no evidence of that name being published by Griseb. 
Therefore, the name was blocked from the source. 

![image](https://github.com/user-attachments/assets/56e3b3ca-f61f-4d81-81d9-43d9c387beab)
