### ISSUE TITLE
duplicate species case - Consolea falcata

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#183]
[Consolea falcata](https://www.checklistbank.org/dataset/303429/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&q=Consolea%20falcata&sortBy=taxonomic&type=EXACT) duplicates, could it be that these names weren't merged   as one of the names has "other" as a rank? is it possible to work around this?

<img width="1206" alt="Captura de pantalla 2024-09-25 a la(s) 12 59 54 p m" src="https://github.com/user-attachments/assets/fb266ed6-8585-4b22-9637-b10cf97c39b6">

**Comment by mdoering** [comment]
indeed thats the cause. We should exclude all names with rank=other. The sector settings only allow you to positively list all accepted ranks, not to list the rejected ones. But I will try to teach the merge to merge such cases

**Comment by mdoering** [comment]
Hm, I cannot reproduce this with the latest code. Let's see if it still happens in the next build.
The GRIIS source claims C. falcata is a synonym and that should be ignored entirely cause the base accepts it:

```
        Cactaceae  [family]
          Consolea macracantha A.Berger  [species] {PROV=true}
            =Consolea falcata (Ekman & Werderm.) F.M.Knuth [other]
```
