### ISSUE TITLE
Check Families under incertae sedis XCOL  2023-07-03

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#20]

**Comment by DianRHR** [comment]
Some of the outstanding findings:
1. Kingdom Incertae Sedis - has no source: from where does it come?
2. All “Families” under “kingdom Incertae Sedis” are names from Zoobank and PaleoDB.
3. There are too many names marked as “Family” but with endings that correspond to subfamily (_inae)  or tribe (_ini) level, or even names of genus level. Some are wrong in Zoobank (Example: [Obisides](https://zoobank.org/NomenclaturalActs/f0be4e41-ab85-4e37-8f62-d2537a764a7e) ) , but some have their taxon rank correct in the original source but wrongly interpreted in [CLB](http://coltest-vh.catalogueoflife.org/dataset/9908/taxon/2db80bf1-6412-40ab-9664-8edcecd3292a) (Example: Ceratinini in [PaleoDB](https://paleobiodb.org/classic/basicTaxonInfo?taxon_no=179683) ).
4. Lots of taxa include "sensu accretion" in the synonyms or as part of the authority. However that annotation, comment or authority doesn’t come from the original source. 
Example: Family Abelisauridae
@zoobank: [Abelisauridae ](http://coltest-vh.catalogueoflife.org/dataset/9908/taxon/36241cdc-48eb-4473-9a5b-9196a0be21d5) Bonaparte and Novas, 1985
	       13 names related: 7 with authority, additional information from external links; 6 without authority.
@ChecklistBank: [Abelisauridae ](http://coltest-vh.catalogueoflife.org/dataset/9908/taxon/36241cdc-48eb-4473-9a5b-9196a0be21d5)(without author) source Zoobank
                 7 names as Synonyms and combinations “sensu accretion”: 4 species, 3 genus. Any of them has “sensu accretion” as a nomenclatural note or nomenclatural status).
5. Many cases where synonym names are wrongly labeled as “accepted”, therefore the genus part of the scientific name does not correspond to the genus name (its parent name): 
[Graphiocrinus timoricus  ](http://coltest-vh.catalogueoflife.org/dataset/9908/taxon/1f98d486-d6ff-4142-97a6-2548a42c85b4)

**Comment by mdoering** [comment]
Compare some of the unplaced families with the GBIF backbone

**Comment by DianRHR** [comment]
the xCOL-W29 has 1555 families under Biota | incertae sedis: 
754 have an exact match in the GBIF backbone: 
- 739 at family level, 15 at genus rank. 
- the sources for these names in xCOL are: Zoobank (51%), PaleoDB (39%), IPNI (4%), AFD (3%), and other 4 sources (1%)
- 64 names are under Biota|Incertae sedis | Missing usage #

Looking at some of these "incertae sedis" families in GBIF, they appear in more than one different checklists datasets in GBIF, some of which include complete higher classification. 
Examples: 
 Alienopteridae: in [GBIF](https://www.gbif.org/species/9450604)  vs in [xCOL ](http://coltest-vh.catalogueoflife.org/dataset/9913/taxon/500f8b10-7269-4101-8815-f386a9183acd) and in [Zoobank ](https://zoobank.org/NomenclaturalActs/11ace691-dcb4-4fc5-ab5b-efee5c3eb4ba)

Helogenidae: in [GBIF](https://www.gbif.org/species/4838184), in [IRMNG](https://www.irmng.org/aphia.php?p=taxdetails&id=112334), in [PaleoDB](https://paleobiodb.org/classic/checkTaxonInfo?taxon_no=355281&is_real_user=1)

Parasitaxaceae: in [GBIF](https://www.gbif.org/species/4055932), in [IPNI](https://www.ipni.org/n/1018751-1), in [Indices Nominum Supragenericorum Plantarum Vascularium](http://www.plantsystematics.org/reveal/pbio/fam/allspgfileP.html)

**Comment by mdoering** [comment]
Alienopteridae is sourced from WoRMS in GBIF, but from ZooBank in xcol. Why was WoRMS not used?

**Comment by camiplata** [comment]
Zoobank, PaleoDB, and IRMNG had been excluded from the xrelease for now, additionally zoobank has been informed about several issues (#31 #32 #34 #36)
