### ISSUE TITLE
Prevent xcol sources to add unranked names above Family level

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#23]
Example off what need to be prevented: PaleoDB with Life

<img width="635" alt="Captura de pantalla 2023-07-03 a la(s) 8 37 01 a m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/d8ab84e0-dbef-45fe-a022-d44a31720b65">

**Comment by mdoering** [comment]
Unranked names should never enter now and match only to existing suprageneric unranked ones in the project
