### ISSUE TITLE
Review W27 xcol release

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#27]

**Comment by mdoering** [comment]
Release ready for review: http://coltest-vh.catalogueoflife.org/dataset/9911/classification?taxonKey=P
Search and sources still not there though.

![image](https://github.com/CatalogueOfLife/xcol/assets/327505/9dec7f86-2cfb-4931-b8be-eb69f419ec2b)

But there are tons of other root taxa and the tree browser shows unranked taxa (Biota!) last, so root is not great to navigate
