### ISSUE TITLE
Check xcol release project documentation

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#28]

**Comment by DianRHR** [comment]
You can find the draft document [here ](https://docs.google.com/document/d/1s6ALuYcD0z15p5CAgw1TYlzW2WGvpb3ywZXwe-_ijew/edit)

**Comment by mdoering** [comment]
Did leave many comments. Phase 2 in my mind is sth very different from what is documented, we should talk about that after summer break.
