### ISSUE TITLE
Where are the unplaced names comming from

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#39]
<img width="674" alt="Captura de pantalla 2023-07-17 a la(s) 8 59 21 a m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/5ae4c168-1816-46c9-89e9-c55fda77d175">

**Comment by camiplata** [comment]
- Real issue: the unplaced names should be at least under incertae sedis

**Comment by camiplata** [comment]
@mdoering incertae sedis kingdom is still missing on the last [XCOl-W38 Release](https://www.dev.checklistbank.org/dataset/268159/classification)

<img width="559" alt="Captura de pantalla 2023-09-24 a la(s) 9 41 40 a m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/07dc21e0-23d9-4b39-a0a2-b35104bb2649">

**Comment by mdoering** [comment]
It is not considered a kingdom and therefore sorts at the end ;)
https://www.dev.checklistbank.org/dataset/268159/taxon/4d8affb8-eb41-44d1-9710-bf1cc1772bf5

**Comment by camiplata** [comment]
I see, then it will be shown in a better way than in GBIF.

On the  other side there are still many unplaced names that should had been placed under incertae sedis

<img width="923" alt="Captura de pantalla 2023-09-24 a la(s) 4 47 12 p m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/2f327f03-f94a-45b0-a69b-2080a025889b">

**Comment by camiplata** [comment]
I'm closing this issue has  #40 is more specific, in general unplaced names have been reduced on the w38 release
