### ISSUE TITLE
Make sure no incertae sedis taxa are on root level

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/xcol#40]
They should all go into a project configurable "incertae sedis" taxon, e.g. kingdom in case of COL

**Comment by camiplata** [comment]
Issue fixed on the [release w39](https://www.dev.checklistbank.org/dataset/268557/about)

<img width="581" alt="Captura de pantalla 2023-09-28 a la(s) 10 08 41 a m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/c71d3676-2029-4d26-8de5-1ed8e96a43b9">
