### ISSUE TITLE
List of test cases - names that potentialy create problems while merging

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#44]
Curate a list of names (github CSV file, google spreadsheet) to verify in a new xcol release.
Initially these names would have to be verified manually for every release, but in the future this should be automated.

- Check old GBIF backbone issues
- Incorrect higher rank placements
- Homonyms
- Prominent species

**Comment by mdoering** [comment]
GBIF issues (open and closed):
 - https://github.com/gbif/portal-feedback/issues?q=is%3Aissue+label%3Abackbone+
 - https://github.com/gbif/checklistbank/issues?q=is%3Aissue+label%3Abackbone+

**Comment by camiplata** [comment]
This is covered with the new project and workflow that we have with GBIF, and perticularly witht the J[SON comments for automation](https://github.com/gbif/backbone-feedback/wiki/JSON-comments-for-automation-%E2%80%90-Experimental) set uP by GBIF
