### ISSUE TITLE
Review download tool in xcol test

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/xcol#45]
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/0eb37dfb-04a3-4a73-a6f2-b660b3b91ca0)

**Comment by mdoering** [comment]
The installation was wrongly configured. But downloading ZIP files on test still serves the frontend files too for some reason.
If you open a (new) download URL like http://coltest-vh.catalogueoflife.org/_jobs/a1/a12d78de-5ec3-4aaa-a656-8d28f4843da2.zip you will see the CLB UI. @DianRHR please just reload the page and you should download the zip file too!

**Comment by DianRHR** [comment]
I am trying to download taxa under kingdom Incertae sedis from the **xcol release**, excluding genera and below.  
It doesn't seems to work when typing sth in the 'Choose root taxon option' (in the download tool )..  probably because the xcol release still need to be indexed ?  
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/95148773-4ab3-4f90-ab30-6c2c14f34f31)


Even that... I proceed and clicked the dowload button... and I got the same error as before.   
  
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/c73b852d-fce2-4988-8c32-d1b8360b035b)

it doesn't work even if I reload the page ... or try to open it in another window

**Comment by mdoering** [comment]
As I have written elsewhere you need to know the identifier that you are trying to download as the search is not working.
Then you can append `?taxonID=XYZ` to the URL and should see the correct name on the right next to the button.

**Comment by mdoering** [comment]
> it doesn't work even if I reload the page ... or try to open it in another window

The backend has not been updated yet

**Comment by mdoering** [comment]
It is deployed now and you should get links like this that work: http://coltest-vh.catalogueoflife.org/_jobs/c8/c80657e3-a143-48fa-ad96-9f2a67495df3.zip
