### ISSUE TITLE
Investigate into bad zoobank names 

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/xcol#5]
Can we use ZooBank names safely or do we need to find better ways of filtering?

**Comment by camiplata** [comment]
I'll list first all observations around zoobank and later sort them out based on their relevance for the xcol release

- Transformation of DwC to COLDP creates duplicated names DwC: 399,276 vs. COLDP: 403.889 example Gallinae, this this issue probably comes from missing or misplaced id's, it creates a lot of noise to browse within Zoobank but probably does not affect the xrelease
- dwc:scientificNameAuthorship has empty values as: <Unspecified Agent>, 46902 records (11%) are affected by it, 43299 genus, 173 species, 1 subspecies,  can be something to fixed at the source, may have a small impact for the xrelease but as species are the less affected It wont be as problematic

**Comment by mdoering** [comment]
With transformation to ColDP you mean importing DwC-A into ChecklistBank? Or exporting it again as ColDP? There is no real DwC to ColDP transformation. 

The Gallinae example is weird indeed. There is no name like that in [GBIF](https://www.gbif.org/species/search?q=Gallinae&dataset_key=c8227bb4-4143-443f-8cb2-51f9576aff14&origin=SOURCE&qField=SCIENTIFIC&advanced=1) which reads the DwCA from http://ipt.bishopmuseum.org:8080/ipt/archive.do?r=zoobank

In ChecklistBank there is 1 source record and 16 (!) denormalised ones!!! That is a clear bug

**Comment by camiplata** [comment]
Yes, I mean importing DwC-A into ChecklistBank, i was assuming that checklistBank transformed all data to CoLDP to properly store everything in the database.

**Comment by DianRHR** [comment]
While reviewing [families ](https://github.com/CatalogueOfLife/xcol/issues/20, I found a good example of a "bad" name from Zoobank: [Alloscirtetina ](http://coltest-vh.catalogueoflife.org/dataset/2037/taxon/5f43e928-1a7c-4bdb-8d00-dbf0607600b4)
which has "Family" as taxon rank but it really is a genus. Besides, it also is misspelled in [Zoobank ](https://zoobank.org/NomenclaturalActs/5f43e928-1a7c-4bdb-8d00-dbf0607600b4), according to the [original source](https://resjournals.onlinelibrary.wiley.com/doi/abs/10.1111/syen.12351), the name is **Alloscirtetica** : 

![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/dc7cb618-d89a-4f12-9832-68233929f97c)

**Comment by mdoering** [comment]
this should be reported to https://zoobank.org/Contact

**Comment by camiplata** [comment]
Specific issues have been documented for zoobank, mean while the checklistBank filters for bare names can escape the remaining "bad names"
