### ISSUE TITLE
BOLD dataset in coltest without data under phylum

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/xcol#53]
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/2740a41d-f16e-40ef-985f-fb6f7267b5cd)
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/57d04c66-aaa4-4417-9768-b78885534f3b)

**Comment by camiplata** [comment]
Needs to be imported

**Comment by camiplata** [comment]
@DianRHR  I think we can close this issue as coltest will be replaced by dev, we can check again on dev once is up an running

**Comment by camiplata** [comment]
Has been fixed on dev

<img width="1329" alt="Captura de pantalla 2023-09-05 a la(s) 8 00 13 p m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/8f79681c-ad9e-46ce-b576-170836a03d1b">
