### ISSUE TITLE
unranked taxa from Bold  is missing from project results

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#56]
Context: Annelida (Phylum) project using as sectors COL WORMS and BOLD
Proyect: cpp_bold_01_annelidae in prod / https://www.checklistbank.org/catalogue/9921/assembly

BOLD sector configuration included unraked taxa
<img width="500" alt="Captura de pantalla 2023-08-17 a la(s) 4 26 57 p m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/d81ed613-4580-4223-8450-5426131c2460">

Nevertheless taxa with BOLD codes are missing, for example: 
https://www.gbif.org/species/10117300 

<img width="500" alt="Captura de pantalla 2023-08-17 a la(s) 4 26 00 p m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/95ac92d4-ef4c-4562-9912-385e7e2860d9">

does not appears on the final assembly, only the genus appears: https://www.checklistbank.org/catalogue/9921/assembly?assemblyTaxonKey=07462d4b-b820-4793-ac1c-b1330e247de3

<img width="601" alt="Captura de pantalla 2023-08-17 a la(s) 4 29 53 p m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/e120559b-0550-4e51-bfc7-a26b1dbb78ff">

I randomly checked several BOLD codes and I find the same, unraked taxa is missing after running the project

**Comment by camiplata** [comment]
I'm re checking with Name types configuration to see if BINS are included

<img width="520" alt="Captura de pantalla 2023-08-17 a la(s) 4 53 05 p m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/64735a07-e623-4f38-b242-242e5277c3bf">

**Comment by camiplata** [comment]
BINs are still missing

**Comment by mdoering** [comment]
@camiplata I understood BOLD OTUs enter the merge results now. Can we close this?
