### ISSUE TITLE
61,992  species "Name parent mismatch" in Paleobiology Database won't be included in xCOL

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/xcol#58]
The current version of PaleoDB has important issues to look at. This is one of the most important. 
https://www.checklistbank.org/dataset/1174/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=parent%20name%20mismatch&limit=50&offset=0&rank=species

We need to decide if still including these names in the xCoL release ... or not.  My first thinking is to exclude the names with this issue. @mdoering did you check this before with the providers?  

These names are included in the GBIF backbone even with a mismatch in their parent: 
https://www.gbif.org/species/11113128
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/51d8436e-1c62-43b6-b1b5-3fa65c7f3713)

https://www.gbif.org/species/9668433
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/f7803483-f0ac-4a13-972f-73f589e25a93)

We need to decide if still including these names in the xCoL release ... or not.

**Comment by mdoering** [comment]
We very much need a new and better data export from PBDB, ideally from someone that knows how the system is organised.

**Comment by mdoering** [comment]
@DianRHR we are the creator of the source

**Comment by mdoering** [comment]
we will write a new converter
