### ISSUE TITLE
consider Korean Flora as xcol source

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/xcol#59]
https://www.checklistbank.org/dataset/62696/about

has very little overlap with gbif & col: https://www.gbif.org/dataset/e09e1e1f-2460-4017-a964-e999abd2bf66

**Comment by DianRHR** [comment]
Seem to be a good option, however: 
1. The total of synonyms (17,037) or "bare names" are not related to an accepted name . In CLB as "Accepted name missing". 
2. Almost half of the bare names (6,613)  have a wrong taxon rank, all are infraspecies but TaxonRank is species. 
3. There are 1172 posible chresonyms not identified in CLB, most of them "bare names". Same name different authors: 

![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/cdf260a9-b71f-4636-be67-b17c8f50d85e)

4. Errors in character encoding (from original source) in the authorship of 1,268 records, not all found in CLB '[Unparsable Authorship]( https://www.checklistbank.org/dataset/62696/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=unparsable%20authorship&limit=50&offset=0)': 

![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/fb649437-57ed-4be5-9616-7881c218fd47)

Based on these findings, I don't consider this as an xcol source.

**Comment by mdoering** [comment]
That indeed does not look good and explains the high numbers of new names
