### ISSUE TITLE
potential new xcol source for ants

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/xcol#60]
a potential new xcol source for ants: https://www.gbif.org/dataset/ec93a739-1681-4b04-b62f-3a687127a17f

gbif.orggbif.org
[Formicidae (ants) - AntBase and xBio:D Cyberinfrastructure, The Ohio State University](https://www.gbif.org/dataset/ec93a739-1681-4b04-b62f-3a687127a17f)
A checklist of the ants (Hymenoptera: Formicidae) of the World

[10:48 Uhr](https://catalogue-of-life.slack.com/archives/C04T8SBLSMV/p1693385306789319)
they have less than 50% overlap with gbif & col
[10:48 Uhr](https://catalogue-of-life.slack.com/archives/C04T8SBLSMV/p1693385324898519)
its just not in clb yet because its license is unspecified. Get in touch?
[10:48 Uhr](https://catalogue-of-life.slack.com/archives/C04T8SBLSMV/p1693385335257499)
oh, contact donat
[10:51 Uhr](https://catalogue-of-life.slack.com/archives/C04T8SBLSMV/p1693385480691939)
its an odd one, there is no data source configured in gbif, just EML. But there is data, so it once existed. Would be good to get in touch I reckon

**Comment by camiplata** [comment]
Norm Johnson is in process of retiring so It looks like we will not be able to add in this sources. Ed and Matt Blister had a work plan to propose him migrate his databases to TaxonWorks. I have no updates on this regard since nov 2023

**Comment by camiplata** [comment]
I ask a month ago about how was this going and got no response, Right now looks like antcat will be taken as the new source for ants, so this datasets have less priority.

I will close the issues as we have already move as far as we can.
