### ISSUE TITLE
GBIF checklists with little COL overlap

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/xcol#61]
Consider the following GBIF checklists as xcol sources as they have little overlap with the GBIF backbone or COL:

>       GBIF dataset_key   |  usage count  | Backbone matches | coverage | title

 -  79f243f4-9c38-4305-997f-fa8ac3089dba |   26741 |   19633 |     73.4 | Taxa Watermanagement the Netherlands (TWN)
 - 7b7d3eba-3a2e-4496-8e41-2773ed400854 |    8535 |    3216 |     37.7 | Cynipoidea (gall wasps) - xBio:D Cyberinfrastructure, The Ohio State University
-  56c83fd9-533b-4b77-a67a-cf521816866e |    7367 |    3297 |     44.8 | Catalogue of Tenebrionidae (Coleoptera) of North America
-  0863cdca-59a2-4549-a67b-5c86d9133e6d |    6131 |    2321 |     37.9 | Diaprioidea - xBio:D Cyberinfrastructure, The Ohio State University
-  1858994c-378e-4e6e-bec9-ee565e3b3be1 |    3212 |     215 |      6.7 | Family-group names in Coleoptera (Insecta)
-  a6ab0cae-13c6-4353-ae90-06194d895f82 |    2840 |    1520 |     53.5 | Digital Catalogue of Biodiversity of Poland — Plantae: Charophyta
-  99c42e58-e4f4-4afd-853e-bc5588e04c8d |     102 |      11 |     10.8 | A checklist of endemic amphibian species of Tanzania
-  0c65dd24-eec6-4584-87ee-b41f9b4e5f44 |      68 |      10 |     14.7 | The checklist of longhorn beetles (Coleoptera: Cerambycidae) from India
-  bab767e9-5f20-41ac-9fef-a5f45521186a |    1105 |     285 |     25.8 | Biodiversidad Estudiada en Trabajos de Grado del Instituto Tecnológico del Putumayo
-  370298ae-494c-485c-9a74-19d46578aa98 |     539 |     156 |     28.9 | Cryptocephalinae of the World
-  a47a335d-4658-4a6d-ac1d-5d5ac841f199 |    1641 |     610 |     37.2 | Proctotrupoidea - xBio:D Cyberinfrastructure, The Ohio State University
-  7b7d3eba-3a2e-4496-8e41-2773ed400854 |    8535 |    3216 |     37.7 | Cynipoidea (gall wasps) - xBio:D Cyberinfrastructure, The Ohio State University
-  0863cdca-59a2-4549-a67b-5c86d9133e6d |    6131 |    2321 |     37.9 | Diaprioidea - xBio:D Cyberinfrastructure, The Ohio State University
-  e09e1e1f-2460-4017-a964-e999abd2bf66 |   39082 |   15064 |     38.5 | Korean Peninsula Flora
-  805272fe-e6f6-4675-9c30-ef8cb56cf84f |     509 |     214 |     42.0 | Listado de las especies de Tenebrionidae (Coleoptera: Tenebrionoidea) de Colombia
-  66e0ec51-d494-43d4-965e-a2cd1462ef54 |     607 |     270 |     44.5 | An illustrated guide to lady beetles (Coleoptera: Coccinellidae) of the Indian Subcontinent. Part 1. Tribe Coccinellini
-  56c83fd9-533b-4b77-a67a-cf521816866e |    7367 |    3297 |     44.8 | Catalogue of Tenebrionidae (Coleoptera) of North America
-  839308e7-2f70-4b90-9765-91b70a24bf8a |     294 |     132 |     44.9 | Lista de las especies de Lycidae (Coleoptera: Elateroidea) de México
-  90731927-c853-4b70-865e-3d06d92a7e76 |     344 |     162 |     47.1 | A checklist of Scoliidae (Insecta: Hymenoptera) from China
-  ec93a739-1681-4b04-b62f-3a687127a17f |   65524 |   32600 |     49.8 | Formicidae (ants) - AntBase and xBio:D Cyberinfrastructure, The Ohio State University
-  3cd73963-ae34-49eb-b8de-d7e914349840 |    2067 |    1046 |     50.6 | Ceraphronoidea - xBio:D Cyberinfrastructure, The Ohio State University
-  e4d6c5d0-8470-438a-93a6-1ae3eef750b1 |   11767 |    6592 |     56.0 | Platygastroidea - xBio:D Cyberinfrastructure, The Ohio State University
-  6c72ae83-e6bf-4ed6-a22a-e435bc24b306 |    1104 |     620 |     56.2 | An Inventory Of The Butterflies Of Manipur, India (Insecta: Lepidoptera)
-  bffe4ff6-abdf-4d7d-a00a-d82e333454b4 |    1375 |     795 |     57.8 | A checklist of chigger mites (Acariformes: Trombiculidae) of Southeast Asia
-  3e3ca27b-44ad-4ea2-af6b-516245293ccf |     859 |     493 |     57.4 | A maximalist approach to the systematics of a biological control agent: Gryon aetherium Talamas, sp. nov. (Hymenoptera, Scelionidae)
-  139f47c3-a59e-454f-8a4c-872686513a87 |     729 |     432 |     59.3 | New combinations in Neotropical Thelypteridaceae
-  852670d8-61c7-46b7-a38c-f459dd15e2f2 |    2459 |    1483 |     60.3 | Lista de las especies de Tenebrionidae (Coleoptera: Tenebrioidea) de México

**Comment by mdoering** [comment]
@DianRHR @camiplata I did not check the quality of any of the lists. There are surprisingly many lists from xBio:D in Ohio. Maybe there is a fundamental problem with those?

**Comment by mdoering** [comment]
Full list of all GBIF checklists and their backbone [coverage.txt](https://github.com/CatalogueOfLife/xcol/files/12473972/coverage.txt)

**Comment by camiplata** [comment]
Thanks! I'll enrich the base coverage data with information about publisher, years, type and other information to have several criteria to sort out the checklist

**Comment by camiplata** [comment]
From the initial list you pointed out we already have several on our reference file, and other still need to be double checked.

**Comment by camiplata** [comment]
For this specific issue these were the results:

<google-sheets-html-origin>
79f243f4-9c38-4305-997f-fa8ac3089dba | Missing higher taxonomy, synonyms to incertae sedis | Taxa Watermanagement the Netherlands (TWN)
-- | -- | --
7b7d3eba-3a2e-4496-8e41-2773ed400854 | broken | Cynipoidea (gall wasps) - xBio:D Cyberinfrastructure, The Ohio State University
56c83fd9-533b-4b77-a67a-cf521816866e | included but needs some fixes | Catalogue of Tenebrionidae (Coleoptera) of North America
0863cdca-59a2-4549-a67b-5c86d9133e6d | broken | Diaprioidea - xBio:D Cyberinfrastructure, The Ohio State University
1858994c-378e-4e6e-bec9-ee565e3b3be1 | Abset hihger taxonomy, Bouchard will give as an updated classification | Family-group names in Coleoptera (Insecta)
a6ab0cae-13c6-4353-ae90-06194d895f82 | Could be added needs a lisence change | Digital Catalogue of Biodiversity of Poland — Plantae: Charophyta
99c42e58-e4f4-4afd-853e-bc5588e04c8d | All bare names and other issues | A checklist of endemic amphibian species of Tanzania
0c65dd24-eec6-4584-87ee-b41f9b4e5f44 | included | The checklist of longhorn beetles (Coleoptera: Cerambycidae) from India
bab767e9-5f20-41ac-9fef-a5f45521186a | Low quality | Biodiversidad Estudiada en Trabajos de Grado del Instituto Tecnológico del Putumayo
370298ae-494c-485c-9a74-19d46578aa98 | To be added | Cryptocephalinae of the World
a47a335d-4658-4a6d-ac1d-5d5ac841f199 | broken | Proctotrupoidea - xBio:D Cyberinfrastructure, The Ohio State University
7b7d3eba-3a2e-4496-8e41-2773ed400854 | broken | Cynipoidea (gall wasps) - xBio:D Cyberinfrastructure, The Ohio State University
0863cdca-59a2-4549-a67b-5c86d9133e6d | broken | Diaprioidea - xBio:D Cyberinfrastructure, The Ohio State University
805272fe-e6f6-4675-9c30-ef8cb56cf84f | included | Listado de las especies de Tenebrionidae (Coleoptera: Tenebrionoidea) de Colombia
66e0ec51-d494-43d4-965e-a2cd1462ef54 | included | An illustrated guide to lady beetles (Coleoptera: Coccinellidae) of the Indian Subcontinent. Part 1. Tribe Coccinellini
839308e7-2f70-4b90-9765-91b70a24bf8a | To be added | Lista de las especies de Lycidae (Coleoptera: Elateroidea) de México
90731927-c853-4b70-865e-3d06d92a7e76 | included | A checklist of Scoliidae (Insecta: Hymenoptera) from China
ec93a739-1681-4b04-b62f-3a687127a17f | broken | Formicidae (ants) - AntBase and xBio:D Cyberinfrastructure, The Ohio State University
3cd73963-ae34-49eb-b8de-d7e914349840 | broken | Ceraphronoidea - xBio:D Cyberinfrastructure, The Ohio State University
e4d6c5d0-8470-438a-93a6-1ae3eef750b1 | broken | Platygastroidea - xBio:D Cyberinfrastructure, The Ohio State University
6c72ae83-e6bf-4ed6-a22a-e435bc24b306 | low quality | An Inventory Of The Butterflies Of Manipur, India (Insecta: Lepidoptera)
bffe4ff6-abdf-4d7d-a00a-d82e333454b4 | included | A checklist of chigger mites (Acariformes: Trombiculidae) of Southeast Asia
3e3ca27b-44ad-4ea2-af6b-516245293ccf | included | A maximalist approach to the systematics of a biological control agent: Gryon aetherium Talamas, sp. nov. (Hymenoptera, Scelionidae)
139f47c3-a59e-454f-8a4c-872686513a87 | To be added / initial excluded but latter review in detail | New combinations in Neotropical Thelypteridaceae
852670d8-61c7-46b7-a38c-f459dd15e2f2 | To be added | Lista de las especies de Tenebrionidae (Coleoptera: Tenebrioidea) de México
