### ISSUE TITLE
United Kingdom Species Inventory (UKSI) - Import Failed

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#68]
https://www.checklistbank.org/dataset/7888/about
https://www.dev.checklistbank.org/dataset/7888/about

**Comment by camiplata** [comment]
It has been failing since may, so we will need to contact the publisher and GBIF

<img width="363" alt="Captura de pantalla 2023-09-13 a la(s) 8 15 12 a m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/551df74e-24bf-4807-98ea-e5ab3e6870dd">

**Comment by camiplata** [comment]
GBIF help desk has been contacted

**Comment by camiplata** [comment]
This was the answer from Andrea in Nov 2023:

"Crawling on our side is working (see https://registry.gbif.org/dataset/dbaa27eb-29e7-4cbb-8eab-3f689cfce116/crawling-history), which suggests that the service as such is up and running, but that they may intentionally open their service only for a limited set of IPs / IP ranges. That occasionally happens if an organization wants to stay in control of more extensive access / downloads of their data. "

@mdoering  is there something we can do on our side knowing this?

**Comment by mdoering** [comment]
No, it needs nbnatlas to fix that. If they do control access by IP addresses we just need to give them the additional range of IPs they need to open up to. I very much dislike publishers restricting access in the first place. What for? How can you place an open license on it and then don't let people access it? 

@MattBlissett what exact IP ranges should be opened for GBIF and COL servers?
https://registry.nbnatlas.org/UKSI/UKSI_DwCA.zip

**Comment by MattBlissett** [comment]
The IP range is 130.225.43.0/24.
