### ISSUE TITLE
Add issues feature to releases

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#69]
To have a adequate overview of the (x)release and improve ist data quality it would be useful to have the issues feature.

How it looks like currently
<img width="294" alt="Captura de pantalla 2023-09-13 a la(s) 10 28 41 a m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/210b9a5c-ae74-4f9b-8831-09926b64a9d2">

We think it should look like this, like on the datasets
<img width="608" alt="Captura de pantalla 2023-09-13 a la(s) 10 27 07 a m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/b27a7b73-49a3-4b7d-8e17-005b320de673">

**Comment by mdoering** [comment]
I have changed the indexing to include issues in projects and releases. Testing now on dev with the xrelease

**Comment by camiplata** [comment]
Issues are still missing on the las Xrelease


<img width="251" alt="Captura de pantalla 2023-11-02 a la(s) 8 49 09 a m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/40647658-fe12-48f5-8f9b-ca3239651364">

**Comment by mdoering** [comment]
this exists at least: 
<img width="555" alt="image" src="https://github.com/CatalogueOfLife/xcol/assets/327505/3687d27c-e52f-4215-8cab-2fe7d55e578c">

**Comment by mdoering** [comment]
check the search filters

**Comment by mdoering** [comment]
The [UI](https://www.dev.checklistbank.org/dataset/271349/issues) requires the import metrics for issues it seems:
https://api.dev.checklistbank.org/dataset/271349/import

**Comment by mdoering** [comment]
Fixed to calculate issues in metrics correctly for releases and projects: https://github.com/CatalogueOfLife/backend/commit/d684ceda3aeaba2622ef01b5d4c2b73cc4dcaf81

**Comment by mdoering** [comment]
closing, but keeping UI issue
