### ISSUE TITLE
Odd duplicates found in xRelease W37

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/xcol#73]
I found several cases of duplicate names: 

**1. Same name, almost same author, one including “Ex” . one source is a GSD**

https://www.dev.checklistbank.org/dataset/265693/classification?taxonKey=8M7C
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/9f485420-7d83-47d8-a784-e144c878196f)

**2. Same name, same author, same classification, different source. one source is a GSD**
https://www.dev.checklistbank.org/dataset/265693/classification?taxonKey=87LK7

![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/41eaf537-3a1c-4b1b-967f-4ed5deb330b6)

**3.  Small difference in author .. one source is a GSD**
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/d04d7e70-ca60-4d1f-82f3-ef7000808825)
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/33753e58-1caa-45ab-9ef0-e7d56616351e)

**4. Different year . Both are new sources (not GSD) . Is this a priority matter?** 
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/85469940-2f4b-4b35-b2d4-332d73ad720b)

**Comment by mdoering** [comment]
I will allow for 1 year difference in authorships. More than that will result in a name considered to be different.
Is that good enough? How should we deal with very different years, can't they be real differences?

**Comment by mdoering** [comment]
Other differences might be managed via decisions manually

**Comment by mdoering** [comment]
Seems to be solved in the latest release: https://www.dev.checklistbank.org/dataset/268159/classification?taxonKey=8M7C

**Comment by camiplata** [comment]
unit test done
