### ISSUE TITLE
xRelease W37: Correct “duplicates” but homonyms not labeled properly

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/xcol#74]
I don't have the links, as the new xrelease is running now. I got the following images yesterday: 

![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/db3b392c-86a2-43c3-82eb-ccf3e2c9dafa)

![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/d86d629e-73ea-4fa3-af0e-e62bf1f4d68d)

![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/b5a60e81-ffa1-4efa-b612-085966d37277)

**However, these are not marked as duplicates because of the subgenus, although both are as accepted names:** 
![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/e18d1763-0a6d-4cec-bd5f-7e0350c9f107)

**Comment by mdoering** [comment]
Same names with different authorships should be merged. Homotypic grouping should clean those up in case they are both accepted (at least if in the same family), so only the highest priority one stays accepted.

In this case the `A.p. (Dejean)` being a synonym of `A. pilleri` is just fine.
Only the duplicate accepted name `Abax parallelepipedus (Piller & Mitterpacher, 1783)` is unexpected.

**Comment by camiplata** [comment]
See also #62
