### ISSUE TITLE
order merge sectors on dev

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/xcol#77]
Many merge sectors on dev lack a priority:
https://www.dev.checklistbank.org/catalogue/3/sector/priority

<img width="873" alt="image" src="https://github.com/CatalogueOfLife/xcol/assets/327505/58532a7b-4073-41e0-8065-6931951c6699">

**Comment by camiplata** [comment]
We set some initial priorities but this will probably chance as we advance on the detailed revision of sources
