### ISSUE TITLE
Kingdom Animalia is duplicated appearing one time outside biota

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#82]
Kingdom Animalia is duplicated appearing one time outside biota with out any species

<img width="646" alt="Captura de pantalla 2023-09-24 a la(s) 9 37 15 a m" src="https://github.com/CatalogueOfLife/backend/assets/5700527/416bac66-f5f8-4302-8493-eded46a84b30">

**Comment by mdoering** [comment]
The search index was missing names, so I started to reindex the release which takes 1-2 hours
