### ISSUE TITLE
Navigation of the tree creates a Request failed with status code 500

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#83]
Every attempt to open a part of the tree creates a"Request failed with status code 500", nevertheless the tree can still be explored

Request failed with status code 500

There was an error processing your request. It has been logged (ID ca3f453b7e8989bd).

HTTP method: GET

https://api.dev.checklistbank.org/nameusage/search?USAGE_ID=GR&DATASET_KEY=268159

<img width="1495" alt="Captura de pantalla 2023-09-24 a la(s) 9 33 55 a m" src="https://github.com/CatalogueOfLife/backend/assets/5700527/048180fa-9e83-47c6-907b-4ca0cf99e372">

**Comment by camiplata** [comment]
Same for browsing a name:

Request failed with status code 500

There was an error processing your request. It has been logged (ID f38fda9f9d1df1c6).

HTTP method: GET

https://api.dev.checklistbank.org/dataset/268159/nameusage/suggest?fuzzy=false&limit=25&q=Apionsoma

Status
500
Internal Server Error

**Comment by mdoering** [comment]
Looks like some other errors talking to ES leaves the client in a bad state for future requests like this.
We need to a) find out what initially went wrong and b) avoid any such errors to take down the ES client: https://github.com/elastic/elasticsearch/issues/49124

**Comment by mdoering** [comment]
The ES client is going corrupt (IO Reactor has stopped) for some reason not logged and find odd Hikari pool logs like that:
> HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=12m52s719ms204?s2ns).

The db pool isnt depleted according to ganglia, so is this GC?
Most log entries are about 45s, but some like above appear to take nearly 13 minutes on a JVM with 21G!

I also see name parser timeouts on regular names in that time period which suggests to me the entire JVM is blocked:
> NameParserGBIF	Parsing timeout for: Abies alba (L.) Mill. sec D?ring 1999

**Comment by mdoering** [comment]
see also https://discuss.elastic.co/t/request-cannot-be-executed-i-o-reactor-status-stopped/195438/4 and https://stackoverflow.com/questions/69255845/elasticsearch-request-cannot-be-executed-i-o-reactor-status-stopped

Maybe memory was rather low at that point

**Comment by mdoering** [comment]
Closing as it is solved for now. But we need to monitor memory needs of xreleases and garbage collection for which I have enabled logs now on dev
