### ISSUE TITLE
Verify homotypic consolidation results

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/xcol#88]
Verify some random examples of changes to the synonymy in the xrelease due to the homotypic grouping.

**Comment by DianRHR** [comment]
I checked examples of species from different groups in the [XCOL-2024-01-11](![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/bd044c55-c7df-4701-b2f3-c2cafbce6440)) and the consolidation seems to be working fine, with some exceptions in the synonyms: 
Aves: 
[Caracara plancus cheriway](https://www.dev.checklistbank.org/dataset/279769/taxon/B74NW) (Jacquin, 1784) 
although.. the grouping didn't happen in 'audobonii' group. 

Reptiles: 
[Chelonia mydas](https://www.dev.checklistbank.org/dataset/279769/taxon/TVGD) (Linnaeus, 1758) 
However, Testudo mydas Linnaeus, 1758 and Chelonia mydas mydas (Linnaeus, 1758) weren't grouped 
and it has three times Testudo marina vulgaris Lacépède, 1758  (without any difference among them). 

Insects: 
[Cratogeomys castanops consitus](https://www.dev.checklistbank.org/dataset/279769/taxon/7JLYH) Nelson & Goldman, 1934

In all cases, all (or almost all) synonyms come from the regular COL checklist, the main difference is that in xCOL the 
homotypic grouping works and shows groups of species, which is an advantage. 
I'm still looking for examples where the synonyms only come from the merging process of additional sources.

**Comment by DianRHR** [comment]
The homotypic sonsolidation is producing good results in [june ](https://www.checklistbank.org/dataset/298210/about) release
