### ISSUE TITLE
Organice unplaced names

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#91]
Organice unplaced names both above biota and inside teh manualy created missing parent
 
![Image](https://github.com/CatalogueOfLife/xcol/assets/5700527/711eedfe-1fc0-478d-a586-f22ec6857b2c)

**Comment by camiplata** [comment]
This issue persist on the [last release of october](https://www.dev.checklistbank.org/dataset/271349/classification),

<img width="400" alt="Captura de pantalla 2023-11-01 a la(s) 1 41 48 p m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/14a69a80-0b6d-48a1-a54c-4739f3fea40f">


All unplaced names are subspecies or varieties,  although they do have a higher taxonomy they have in common the issue  "parent species missing", I think this is the reason of the failed placement into the assembly.

Some examples below for taxa (subspecies and varieties) with higher taxonomy but missing parent species:

<img width="800" alt="Captura de pantalla 2023-11-01 a la(s) 1 41 21 p m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/f2b16a27-20d8-4555-8d89-aecdfdb4b5e7">

<img width="800" alt="Captura de pantalla 2023-11-01 a la(s) 1 40 48 p m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/cd208b82-e5f1-4c04-820d-7f20e2b2e9ac">



@mdoering Maybe we can improve the code so it makes the placement taking into account at least two ranks above the given taxon.

**Comment by DianRHR** [comment]
also reported in #100

**Comment by mdoering** [comment]
Looking at the logs I see this happens because the implicit species is considered a synonym by COL or some higher priority source:

> % grep -B 1 -A 3 -n "Pinnularia undulata var." job.log
> 1815426-2023-12-04 18:11:15,787 DEBUG TreeBaseHandler             2144 Created SYNONYM SPECIES usage Pinnularia undulata W. Greg. from source 2144:~NYl
> 1815427:2023-12-04 18:11:15,789 DEBUG SyncNameUsageRules          2144 remove authorship from botanical autonym Pinnularia undulata var. undulata
> 1815428:2023-12-04 18:11:15,789 DEBUG TreeMergeHandler            2144 process SYNONYM VARIETY Pinnularia undulata var. undulata -> KINGDOM Chromista* | SUBKINGDOM Harosa | INFRAKINGDOM Halvaria | SUPERPHYLUM Heterokonta | PHYLUM Ochrophyta* | CLASS Bacillariophyceae Haeckel* | SUBCLASS Bacillariophycidae Mann | ORDER Naviculales Bessey* | FAMILY Pinnulariaceae Mann* | GENUS Caloneis Cleve* | SPECIES Caloneis undulata (W. Greg.) Krammer in Krammer & Lange-Bert.* | VARIETY Pinnularia undulata var. undulata
> 1815429:2023-12-04 18:11:15,792 DEBUG TreeMergeHandler            2144 Pinnularia undulata var. undulata matches [NONE] 275521
> 1815430:2023-12-04 18:11:15,793 DEBUG TreeBaseHandler             2144 Created SYNONYM VARIETY usage Pinnularia undulata var. undulata from source 2144:~NYm
> 1815431-2023-12-04 18:11:15,796 DEBUG TreeMergeHandler            2144 process ACCEPTED SPECIES Caloneis fontinalis (Grunow) Lange-Bertalot & E. Reichardt in Lange-Bertalot & Metzeltin -> KINGDOM Chromista* | SUBKINGDOM Harosa | INFRAKINGDOM Halvaria | SUPERPHYLUM Heterokonta | PHYLUM Ochrophyta* | CLASS Bacillariophyceae Haeckel* | SUBCLASS Bacillariophycidae Mann | ORDER Naviculales Bessey* | FAMILY Pinnulariaceae Mann* | GENUS Caloneis Cleve* | SPECIES Caloneis fontinalis (Grunow) Lange-Bertalot & E. Reichardt in Lange-Bertalot & Metzeltin
> 1815432-2023-12-04 18:11:15,798 DEBUG TreeMergeHandler            2144 Caloneis fontinalis (Grunow) Lange-Bertalot & E. Reichardt in Lange-Bertalot & Metzeltin matches [NONE] 275521
> 1815433-2023-12-04 18:11:15,812 DEBUG TreeBaseHandler             2144 Created ACCEPTED SPECIES usage Caloneis fontinalis (Grunow) Lange-Bertalot & E. Reichardt in Lange-Bertalot & Metzeltin from source 2144:~NYn
> --
> 1815941-2023-12-04 18:11:17,578 DEBUG TreeBaseHandler             2144 Created ACCEPTED SPECIES usage Pinnularia tibetana Hust. from source 2144:~NbK
> 1815942:2023-12-04 18:11:17,581 DEBUG TreeMergeHandler            2144 process ACCEPTED VARIETY Pinnularia undulata var. subundulata -> KINGDOM Chromista* | SUBKINGDOM Harosa | INFRAKINGDOM Halvaria | SUPERPHYLUM Heterokonta | PHYLUM Ochrophyta* | CLASS Bacillariophyceae Haeckel* | SUBCLASS Bacillariophycidae Mann | ORDER Naviculales Bessey* | FAMILY Pinnulariaceae Mann* | GENUS Pinnularia Ehrenberg* | VARIETY Pinnularia undulata var. subundulata
> 1815943:2023-12-04 18:11:17,583 DEBUG TreeMergeHandler            2144 Pinnularia undulata var. subundulata matches [NONE] 275521
> 1815944-2023-12-04 18:11:17,589 DEBUG TreeBaseHandler             2144 Found implicit SPECIES Pinnularia undulata in project
> 1815945:2023-12-04 18:11:17,591 DEBUG TreeBaseHandler             2144 Implicit SPECIES Pinnularia undulata is a synonym, use accepted name null as parent and mark new name Pinnularia undulata var. subundulata [VARIETY] {4517} as provisional
> 1815946:2023-12-04 18:11:17,595 DEBUG TreeBaseHandler             2144 Created PROVISIONALLY_ACCEPTED VARIETY usage Pinnularia undulata var. subundulata from source 2144:~NbL
> 1815947-2023-12-04 18:11:17,598 DEBUG TreeMergeHandler            2144 process ACCEPTED SPECIES Pinnularia divergentissima -> KINGDOM Chromista* | SUBKINGDOM Harosa | INFRAKINGDOM Halvaria | SUPERPHYLUM Heterokonta | PHYLUM Ochrophyta* | CLASS Bacillariophyceae Haeckel* | SUBCLASS Bacillariophycidae Mann | ORDER Naviculales Bessey* | FAMILY Pinnulariaceae Mann* | GENUS Pinnularia Ehrenberg* | SPECIES Pinnularia divergentissima
> 1815948-2023-12-04 18:11:17,600 DEBUG TreeMergeHandler            2144 Pinnularia divergentissima matches [NONE] 275521
> 1815949-2023-12-04 18:11:17,609 DEBUG TreeBaseHandler             2144 Created ACCEPTED SPECIES usage Pinnularia divergentissima from source 2144:~NbM
> --
> 14886202-	at java.base/java.lang.Thread.run(Thread.java:834)
> 14886203:2023-12-04 19:53:40,387 WARN  TreeMergeHandler            2011 Unable to process Taxon{Pinnularia undulata var. continua Cleve-Euler, 1955 [urn:lsid:marinespecies.org:taxname:971549]} with parent urn:lsid:marinespecies.org:taxname:964436. IllegalStateException:Usage parent urn:lsid:marinespecies.org:taxname:964436 not found for Pinnularia undulata var. continua Cleve-Euler, 1955
> 14886204:java.lang.IllegalStateException: Usage parent urn:lsid:marinespecies.org:taxname:964436 not found for Pinnularia undulata var. continua Cleve-Euler, 1955
> 14886205-	at life.catalogue.matching.MatchedParentStack.push(MatchedParentStack.java:171)
> 14886206-	at life.catalogue.assembly.TreeMergeHandler.acceptThrowsNoCatch(TreeMergeHandler.java:109)
> 14886207-	at life.catalogue.assembly.TreeMergeHandler.acceptThrows(TreeMergeHandler.java:88)
> --
> 14886225-	at java.base/java.lang.Thread.run(Thread.java:834)
> 14886226:2023-12-04 19:53:40,387 WARN  TreeMergeHandler            2011 Unable to process Taxon{Pinnularia undulata var. dubia Cleve-Euler, 1955 [urn:lsid:marinespecies.org:taxname:971550]} with parent urn:lsid:marinespecies.org:taxname:964436. IllegalStateException:Usage parent urn:lsid:marinespecies.org:taxname:964436 not found for Pinnularia undulata var. dubia Cleve-Euler, 1955
> 14886227:java.lang.IllegalStateException: Usage parent urn:lsid:marinespecies.org:taxname:964436 not found for Pinnularia undulata var. dubia Cleve-Euler, 1955
> 14886228-	at life.catalogue.matching.MatchedParentStack.push(MatchedParentStack.java:171)
> 14886229-	at life.catalogue.assembly.TreeMergeHandler.acceptThrowsNoCatch(TreeMergeHandler.java:109)
> 14886230-	at life.catalogue.assembly.TreeMergeHandler.acceptThrows(TreeMergeHandler.java:88)
> --
> 14886318-	at java.base/java.lang.Thread.run(Thread.java:834)
> 14886319:2023-12-04 19:53:40,388 WARN  TreeMergeHandler            2011 Unable to process Taxon{Pinnularia undulata var. stauroneiformis Cleve-Euler, 1955 [urn:lsid:marinespecies.org:taxname:671878]} with parent urn:lsid:marinespecies.org:taxname:985061. IllegalStateException:Usage parent urn:lsid:marinespecies.org:taxname:985061 not found for Pinnularia undulata var. stauroneiformis Cleve-Euler, 1955
> 14886320:java.lang.IllegalStateException: Usage parent urn:lsid:marinespecies.org:taxname:985061 not found for Pinnularia undulata var. stauroneiformis Cleve-Euler, 1955
> 14886321-	at life.catalogue.matching.MatchedParentStack.push(MatchedParentStack.java:171)
> 14886322-	at life.catalogue.assembly.TreeMergeHandler.acceptThrowsNoCatch(TreeMergeHandler.java:109)
> 14886323-	at life.catalogue.assembly.TreeMergeHandler.acceptThrows(TreeMergeHandler.java:88)
> --
> 14886341-	at java.base/java.lang.Thread.run(Thread.java:834)
> 14886342:2023-12-04 19:53:40,389 WARN  TreeMergeHandler            2011 Unable to process Taxon{Pinnularia undulata var. subundulata Grunow, 1882-1885 [urn:lsid:marinespecies.org:taxname:672420]} with parent urn:lsid:marinespecies.org:taxname:985061. IllegalStateException:Usage parent urn:lsid:marinespecies.org:taxname:985061 not found for Pinnularia undulata var. subundulata Grunow, 1882-1885
> 14886343:java.lang.IllegalStateException: Usage parent urn:lsid:marinespecies.org:taxname:985061 not found for Pinnularia undulata var. subundulata Grunow, 1882-1885
> 14886344-	at life.catalogue.matching.MatchedParentStack.push(MatchedParentStack.java:171)
> 14886345-	at life.catalogue.assembly.TreeMergeHandler.acceptThrowsNoCatch(TreeMergeHandler.java:109)
> 14886346-	at life.catalogue.assembly.TreeMergeHandler.acceptThrows(TreeMergeHandler.java:88)
> --
> 14886364-	at java.base/java.lang.Thread.run(Thread.java:834)
> 14886365:2023-12-04 19:53:40,389 WARN  TreeMergeHandler            2011 Unable to process Taxon{Pinnularia undulata var. nipponica Skvortzow, 1936 [urn:lsid:marinespecies.org:taxname:686898]} with parent urn:lsid:marinespecies.org:taxname:985061. IllegalStateException:Usage parent urn:lsid:marinespecies.org:taxname:985061 not found for Pinnularia undulata var. nipponica Skvortzow, 1936
> 14886366:java.lang.IllegalStateException: Usage parent urn:lsid:marinespecies.org:taxname:985061 not found for Pinnularia undulata var. nipponica Skvortzow, 1936
> 14886367-	at life.catalogue.matching.MatchedParentStack.push(MatchedParentStack.java:171)
> 14886368-	at life.catalogue.assembly.TreeMergeHandler.acceptThrowsNoCatch(TreeMergeHandler.java:109)
> 14886369-	at life.catalogue.assembly.TreeMergeHandler.acceptThrows(TreeMergeHandler.java:88)
> --
> 14886387-	at java.base/java.lang.Thread.run(Thread.java:834)
> 14886388:2023-12-04 19:53:40,389 WARN  TreeMergeHandler            2011 Unable to process Taxon{Pinnularia undulata var. sibirica Skvortzow, 1938 [urn:lsid:marinespecies.org:taxname:686899]} with parent urn:lsid:marinespecies.org:taxname:985061. IllegalStateException:Usage parent urn:lsid:marinespecies.org:taxname:985061 not found for Pinnularia undulata var. sibirica Skvortzow, 1938
> 14886389:java.lang.IllegalStateException: Usage parent urn:lsid:marinespecies.org:taxname:985061 not found for Pinnularia undulata var. sibirica Skvortzow, 1938
> 14886390-	at life.catalogue.matching.MatchedParentStack.push(MatchedParentStack.java:171)
> 14886391-	at life.catalogue.assembly.TreeMergeHandler.acceptThrowsNoCatch(TreeMergeHandler.java:109)
> 14886392-	at life.catalogue.assembly.TreeMergeHandler.acceptThrows(TreeMergeHandler.java:88)


In these cases we move the infraspecific name to the accepted name of the synonym, in the case of _Pinnularia undulata var. subundulata_ the log says `null` - which is why it ends up on root!

**Comment by mdoering** [comment]
Happens when the accepted was just created and the batch session isn't flushed. Flushing it now and if it still doesn't exist we rather skip those names
