### ISSUE TITLE
Create Release QC document/checklist

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#95]

**Comment by camiplata** [comment]
V1 of the document [here](https://docs.google.com/document/d/15oA6G0lGc_0F-P59Szln45_ps0fuL3QySeii6VXIO7Y/edit)

**Comment by DianRHR** [comment]
A draft document with the key aspects to consider in the revision is [here ](https://docs.google.com/document/d/15oA6G0lGc_0F-P59Szln45_ps0fuL3QySeii6VXIO7Y/edit?usp=sharing)

**Comment by mdoering** [comment]
superceded by validations scripts at https://github.com/CatalogueOfLife/xcol
