### ISSUE TITLE
 xsources did not merge or partially merged

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#98]
Checking issue #87 I noticed the Tenebrionidae Catalog had a partial merge, similarly to what may had happened for [Clements](https://github.com/CatalogueOfLife/data/issues/574).

This probably happened with more sources.

**Comment by camiplata** [comment]
There is some evidence that this also might had happened with WORMS see #65

**Comment by camiplata** [comment]
There still something odd happening with the merge of [Catalogue of Tenebrionidae (Coleoptera) of North America](https://www.dev.checklistbank.org/dataset/2048/about) and probably with other sources:

1. Only four taxa were added: https://www.dev.checklistbank.org/dataset/273939/names?SECTOR_DATASET_KEY=2048&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&sortBy=taxonomic

![Image](https://github.com/CatalogueOfLife/xcol/assets/5700527/c3e545c6-fbdc-4a3a-a0fc-d5ad23b27548)

Names as[ Mycetochara haldemani (LeConte, 1866)](https://www.dev.checklistbank.org/dataset/2048/taxon/2787) are completely missing from the assembly

2. Plazi is having higher priority over this catalogue, [all the names that come from Plazi of the genus Mycetochara should have come from the catalogue ](https://www.dev.checklistbank.org/dataset/273939/classification?taxonKey=~1Lam)


![Image](https://github.com/CatalogueOfLife/xcol/assets/5700527/fdaac1a1-f2a9-4aed-a25c-18b60289b9b7)


---------

Worms hasn't been merge either buy I'm guessing this is due to the "Unspecified license". I'm right?

---------

On the other side It looks like [Clements did merge this time](https://www.dev.checklistbank.org/dataset/273939/names?SECTOR_DATASET_KEY=2013&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=50&reverse=false&sortBy=taxonomic)

**Comment by DianRHR** [comment]
the XCOL-2023-11-20 I found that different genus of the same family ... from the same source were merged differently: 
Examples: Pelonema and Peloploca, both genera in [Pelonemataceae ](https://www.dev.checklistbank.org/dataset/2041/classification?taxonKey=urn%3Alsid%3Adyntaxa.se%3ATaxon%3A2003912)were merged differently (both from DynTaxa): 
[Pelonema ](https://www.dev.checklistbank.org/dataset/273939/taxon/~1bJr) was properly located in Bacteria | Negibacteria | Bacteroidetes | Sphingobacteriia | Sphingobacteriales | Pelonemataceae

However, [Peloploca ](https://www.dev.checklistbank.org/dataset/273939/taxon/~Ogf )was merged directly under Biota

**Comment by mdoering** [comment]
There are [4 names merged](https://www.dev.checklistbank.org/dataset/275521/names?SECTOR_DATASET_KEY=2048&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&sortBy=taxonomic
) from Catalogue of Tenebrionidae:

- Colparthrum Kirsch, 1866 | accepted | genus
- Micrarmalia Casey, 1907 | accepted | genus
- Emmenastus constrictus Champion, 1892 | synonym of Micrarmalia constricta (Champion, 1892) 
- Micrarmalia constricta (Champion, 1892) | accepted | species 

Note also that the CoT has a broken sector:
https://www.dev.checklistbank.org/catalogue/3/sector?limit=100&offset=0&subjectDatasetKey=2048

**Comment by camiplata** [comment]
This merging problem has been fixed

<img width="1243" alt="Captura de pantalla 2024-03-14 a la(s) 3 12 02 p m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/b23c844b-a302-4591-9c53-059b3042aee5">
<img width="1210" alt="Captura de pantalla 2024-03-14 a la(s) 3 17 06 p m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/ce7ebd01-6cf8-4b4c-bc5f-d72ae68c41a0">
